### ISSUE TITLE
Not knowing server costs

### ISSUE THREAD

**Issue by InfinitySamurai** [TotomInc/skid-inc#16]
You can't tell what the cost of a server is without trying to buy it. Perhaps add it to the help tool tip?

**Comment by InfinitySamurai** [comment]
Nevermind, you can do buy -info. Should have played longer before making an issue

**Comment by TotomInc** [comment]
No problem, but we should look for an easier way to check prices instead of always typing `buy -info`.

Do you have a suggestion for this?

**Comment by TotomInc** [comment]
Oh, btw you want to take part of the SkidInc community and join the subreddit ([/r/skidinc](https://www.reddit.com/r/skidinc)? When the game will be in closed-alpha testing, you will be able to post all what you think about the game (feedback, ideas, bugs), and will be notified of any new version.

**Comment by InfinitySamurai** [comment]
Hey, I have joined. Reddit user is Rysty :+1:

**Comment by TotomInc** [comment]
Oh okay it's you! :smile: 

Let me know if you have any suggestion for a better price display for the servers!
