### ISSUE TITLE
can't run game with http-server, needs to be added to README.md

### ISSUE THREAD

**Issue by InfinitySamurai** [TotomInc/skid-inc#17]
What needs to be installed to be able to run `http-server .`? This needs to be defined in the README.md

**Comment by InfinitySamurai** [comment]
I'm guessing this should probably be a part of the initial npm install, but by default I can't run that command after running the npm install

**Comment by TotomInc** [comment]
Skid-Inc use NodeJS, especially the `http-server` module. You need to install NodeJS on your computer. When it's done, run a cmd in the skidinc folder and run the following command `npm i`. This should install all devdeps of the project, including `http-server`.

But I still recommend to install `http-server` module globally, so like this `npm install http-server -g`.

I will add all the required informations in the README.md asap, thanks for the reminder.
