### ISSUE TITLE
Mismatch between `team` command and `hackers` command, and their tooltips

### ISSUE THREAD

**Issue by InfinitySamurai** [TotomInc/skid-inc#18]
typing `team` gives a response of `[ERROR] You must use **hackers** with arguments....`

typing `hackers` gives `[ERROR] Unknown arguments.`

There is a mismatch between the tooltips, and the commands that actually exists. 
Is there supposed to be two commands, team and hackers? or are hackers supposed to be team?

**Comment by InfinitySamurai** [comment]
looks to me that you've changed team to hackers and changed everything except the base command

**Comment by TotomInc** [comment]
Yeah, it's because the file is named `team.js` and it deals about hackers. I just need to change the strings in the help. Or maybe you want to do it?

**Comment by InfinitySamurai** [comment]
Yeah I can do it. Wasn't sure what needed to be changed where. So should the command be team still? And the help string just need to be changed to reflect this?

**Comment by TotomInc** [comment]
Command should be `hackers` by default. If you think `team` is better, we will change it to `team`! :wink:

**Comment by InfinitySamurai** [comment]
Nah I think hackers is better. So if the file name is causing the command to be team, do we need to change the filename and update other places that reference it?

**Comment by TotomInc** [comment]
Change the filename, and stay with `hackers` as command.

**Comment by TotomInc** [comment]
I have created a new branch for you, please put your code changes in the `beta-0.06-pr` branch.

Thanks! :smiley:

**Comment by InfinitySamurai** [comment]
Yeah I don't know what I'm doing. All I've managed to do is break it. Found all the instances of game.team and changed it to game.hackers, changed the filename. I don't really know :p

**Comment by TotomInc** [comment]
You changed the filename of the file to load in the `index.html`? Maybe you forgot to change it there, so `hackers.js` was not loaded.

**Comment by InfinitySamurai** [comment]
Yeah didn't change it in index.html. That might be it

**Comment by TotomInc** [comment]
Let me know if you have any problems, or push it to the `beta-0.06-pr` branch and we will work on it to solve any bugs. :wink:
