### ISSUE TITLE
Remove `-help` requirement from `buy -server -help`

### ISSUE THREAD

**Issue by InfinitySamurai** [TotomInc/skid-inc#20]
I feel it's a bit redundant to make that extra step. Perhaps there is some reason for it later on if you add more options. If I type `buy -server`, it should be obvious that I want a list of servers that are available and their costs

**Comment by TotomInc** [comment]
I think I have done the same for abilities, but if we do it for `buy -server` we must also do it for `buy -ability`.

**Comment by InfinitySamurai** [comment]
Yes absolutely, and buy -hacker. I find it really annoying when I run `buy -server` and then it's like "nah, gotta use help" and I forget every time. If there are more options that you are going to place, then it might be required

**Comment by TotomInc** [comment]
Okay, if you want to do the changes for server, ability and hacker, you can do it, it's a good QoL.
