### ISSUE TITLE
Don't have access to push to the beta-0.060pr branch

### ISSUE THREAD

**Issue by InfinitySamurai** [TotomInc/skid-inc#22]
Is there a place we can talk with instant chat or something?

**Comment by TotomInc** [comment]
I added you as collaborator, it should be good now. If not let me know.

One day I made a private chat room, I will try to make one for the project.

**Comment by InfinitySamurai** [comment]
Cool, thankyou

**Comment by TotomInc** [comment]
[Here is the chatroom](https://us20.chatzy.com/28399329514591)
