### ISSUE TITLE
Can't use some commands

### ISSUE THREAD

**Issue by InfinitySamurai** [TotomInc/skid-inc#28]
When I try to use a command such as `hack -place mini_market` and press enter, it doesn't do anything at all. If I add any other character to it, or make it 1 character less it gives me an error. Something is wrong with the redirection of the function

**Comment by Hedrauta** [comment]
Dev is working on it hardly.... please be patient till bugfix is released ;)

**Comment by TotomInc** [comment]
0.08 is totally bugged, I'm really sorry.

However, it's currently fixed in 0.09, the branch have not been merged on stable yet, but you can still play the game from the 0.09 branch with all bugs fixed.

I will close it once merge 0.09 to stable.

**Comment by TotomInc** [comment]
It's good, beta-0.09 have been merged to stable branch. Just waiting for the host of the alpha-tester server to update the repo.
