### ISSUE TITLE
New lines at bottom

### ISSUE THREAD

**Issue by jackusm** [TotomInc/skid-inc#31]
I think this should act more like a real terminal, where new lines are at the bottom rather than the top. Currently, especially with multiple new lines, it is really messy to read.

**Comment by TotomInc** [comment]
So I can add a margin on both bottom and top on lines, it should help to read.

**Comment by W1-PopelierE** [comment]
in a normal cmd/terminal new lines spawn at the bottom and not on top

**Comment by TotomInc** [comment]
Fixed on the next version.
