### ISSUE TITLE
job

### ISSUE THREAD

**Issue by W1-PopelierE** [TotomInc/skid-inc#34]
when a job is offered this is a part of the message to enter that command:
"jobs respond accept/reject."

jobs isn't a registered command. Job is (without the "s" at the end)

**Comment by TotomInc** [comment]
This is currently fixed on my dev version, but still not pushed.

I'm taking a break on the game since I started school a few weeks ago, so I don't have much time to program.

**Comment by W1-PopelierE** [comment]
ah i know the feeling haha

**Comment by W1-PopelierE** [comment]
its looking awesome btw. Great job

**Comment by TotomInc** [comment]
Thanks, the next update will include botnets. Stay tuned, take a look at /r/skidinc
